sudo: required

env:
  PKG_NAME=docker-robotframework

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t docker-robotframework:ci .

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push
  on:
    branch: main
